/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DA1.from;

import DA1.main.Main;
import DA1.model.MauSac;

import DA1.service.MauSacService;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicTabbedPaneUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author namtr
 */
public class JFAddMauSac extends javax.swing.JFrame {

    int seen;

    DefaultTableModel tbl = new DefaultTableModel();
    ArrayList<MauSac> list = new ArrayList<>();
    int rowselect;

    /**
     * Creates new form JFAddMauSac
     */
    public JFAddMauSac() {

        initComponents();
        setLocationRelativeTo(null);
        FillToTableThuoTinh();
        FillToTableThungracThuoTinh();
        setDefaultCloseOperation(Main.DISPOSE_ON_CLOSE);
    }

    public void FillToTableThuoTinh() {
        tbl = (DefaultTableModel) tblThuocTinh.getModel();
        tbl.setRowCount(0);
        list = (ArrayList<MauSac>) MauSacService.selectTblThuoTinh();
        for (MauSac thuocTinh : list) {
            tbl.addRow(new Object[]{thuocTinh.getId(), thuocTinh.getTenMau()});
            
        }
    }

    public void FillToTableThungracThuoTinh() {
        tbl = (DefaultTableModel) tblThungRacThuocTinh.getModel();
        tbl.setRowCount(0);
        list = (ArrayList<MauSac>) MauSacService.selectTblThungRacThuoTinh();
        for (MauSac thuocTinh : list) {
            tbl.addRow(new Object[]{thuocTinh.getId(), thuocTinh.getTenMau()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtThuocTinh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        table = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThuocTinh = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThungRacThuocTinh = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnKhoiPhuc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Màu Sắc");

        txtThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThuocTinhActionPerformed(evt);
            }
        });

        jLabel2.setText("Thêm nhanh");

        tblThuocTinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên thuộc tính", "Chọn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThuocTinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThuocTinhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThuocTinh);
        if (tblThuocTinh.getColumnModel().getColumnCount() > 0) {
            tblThuocTinh.getColumnModel().getColumn(0).setResizable(false);
            tblThuocTinh.getColumnModel().getColumn(1).setResizable(false);
            tblThuocTinh.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
        );

        table.addTab("Thuộc tính", jPanel2);

        tblThungRacThuocTinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên thuộc tính", "Chọn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblThungRacThuocTinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThungRacThuocTinhMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblThungRacThuocTinh);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
        );

        table.addTab("Thùng rác", jPanel3);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        btnKhoiPhuc.setText("Khôi phục");
        btnKhoiPhuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhoiPhucMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKhoiPhuc, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnSua)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addGap(18, 18, 18)
                .addComponent(btnKhoiPhuc)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(table)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThuocTinhActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtThuocTinhActionPerformed

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        String ThuocTinh = txtThuocTinh.getText();
        if (!ThuocTinh.isEmpty()) {
            JOptionPane.showMessageDialog(this, MauSacService.add(ThuocTinh));
            FillToTableThuoTinh();
            FillToTableThungracThuoTinh();
        } else {
            JOptionPane.showMessageDialog(this, "Không được đê trống");
        }

    }//GEN-LAST:event_btnThemMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        seen = table.getSelectedIndex();
        System.out.println("bảng đang chọn là: " + seen);

        if (seen == 0) { // Nếu đang ở tab thuộc tính
            // Xóa thuộc tính và đưa vào thùng rác
            boolean itemDeleted = false;
            tbl = (DefaultTableModel) tblThuocTinh.getModel();
            for (int i = 0; i < tbl.getRowCount(); i++) {
                Boolean checked = (Boolean) tbl.getValueAt(i, 2);
                if (checked != null && checked) {
                    itemDeleted = true;
                    Integer id = (Integer) tbl.getValueAt(i, 0);
                    MauSacService.GetToGaber(id);
                }
            }
            if (itemDeleted) {
                FillToTableThuoTinh();
                FillToTableThungracThuoTinh();
            } else {
                System.out.println("Bạn chưa chọn đối tượng nào");
            }
        } else if (seen == 1) { // Nếu đang ở tab thùng rác
            // Xóa sản phẩm
            boolean itemDeleted = false;
            tbl = (DefaultTableModel) tblThungRacThuocTinh.getModel();
            for (int i = 0; i < tbl.getRowCount(); i++) {
                Boolean checked = (Boolean) tbl.getValueAt(i, 2);
                if (checked != null && checked) {
                    itemDeleted = true;
                    Integer id = (Integer) tbl.getValueAt(i, 0);
                    MauSacService.delete(id);
                }
            }
            if (itemDeleted) {
                FillToTableThuoTinh();
                FillToTableThungracThuoTinh();
            } else {
                System.out.println("Bạn chưa chọn đối tượng nào");
            }
        }


    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        rowselect = tblThuocTinh.getSelectedRow();
         tbl = (DefaultTableModel) tblThuocTinh.getModel();
        if (rowselect == -1) {
            System.out.println("Bạn chưa chọn đối tượng nào");
        } else {
            System.out.println("Dòng được chọn để sửa: " + rowselect);
            int id = (int) tbl.getValueAt(rowselect, 0);
            String ten = txtThuocTinh.getText();
            MauSac tt = new MauSac(id, ten);
            System.out.println("Đối tượng là "+ten +"ID là : "+id);
            MauSacService.update(tt);
            FillToTableThuoTinh();
            FillToTableThungracThuoTinh();
            System.out.println("Đã sửa thành công");
        }
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnKhoiPhucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhoiPhucMouseClicked
        boolean itemSelected = false;
        tbl = (DefaultTableModel) tblThungRacThuocTinh.getModel();
        for (int i = 0; i < tbl.getRowCount(); i++) {
            Boolean checked = (Boolean) tbl.getValueAt(i, 2);
            if (checked != null && checked) {
                itemSelected = true;
                Integer id = (Integer) tbl.getValueAt(i, 0);
                MauSacService.returnItem(id);
            }
        }
        if (itemSelected) {
            FillToTableThuoTinh();
            FillToTableThungracThuoTinh();
        } else {
            System.out.println("Bạn chưa chọn đối tượng nào");
        }
    }//GEN-LAST:event_btnKhoiPhucMouseClicked


    private void tblThuocTinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThuocTinhMouseClicked
//        rowselect = tblThuocTinh.getSelectedRow();
//        txtThuocTinh.setText(tblThuocTinh.getValueAt(rowselect, 1).toString());
    }//GEN-LAST:event_tblThuocTinhMouseClicked

    private void tblThungRacThuocTinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThungRacThuocTinhMouseClicked
//        rowselect = tblThungRacThuocTinh.getSelectedRow();
//        txtThuocTinh.setText(tblThungRacThuocTinh.getValueAt(rowselect, 1).toString());
    }//GEN-LAST:event_tblThungRacThuocTinhMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAddMauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAddMauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAddMauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAddMauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAddMauSac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhoiPhuc;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane table;
    private javax.swing.JTable tblThungRacThuocTinh;
    private javax.swing.JTable tblThuocTinh;
    private javax.swing.JTextField txtThuocTinh;
    // End of variables declaration//GEN-END:variables
}
